### ISSUE TITLE
seize=1 in PointingDevice URI with Java

### ISSUE THREAD

**Issue by mnancel** [INRIA/libpointing#15] opened 2017-01-31 17:17 UTC
Hi,

I'm using the Java bindings of libpointing on a MacBook Pro 13" (OS version 10.11.6, Java 8). 

I'm trying to block the events from the trackpad to reach my Java window in order to control the cursor's gain function. To do so, I create my PointingDevice with a URI that ends with "&seize=1", but the cursor keeps moving.

Am I doing something wrong, or has this functionality not been ported to Java?

Thanks a lot.

**Comment by Izzatbek** [comment] 2017-02-01 12:25
Hi @mnancel. The problem is not in the bindings. Seems like that`&seize=1` is not working. I will try to take a look in a few days and fix this issue.

**Comment by casiez** [comment] 2017-02-01 13:04
I confirm this has nothing to do with the bindings. I tried consoleExample on Sierra and it did not work.

On macOS, seize is handled using kIOHIDOptionsTypeSeizeDevice option when opening the device.
See line 61 in  libpointing/pointing/input/osx/osxPointingDeviceManager.cpp

It should still be supported by macOS10.12+ https://developer.apple.com/reference/iokit/1556660-anonymous/kiohidoptionstypeseizedevice?language=objc

**Comment by casiez** [comment] 2017-02-03 21:35
Using event tap is a possible workaround but i may not work according to: http://stackoverflow.com/questions/4518559/consuming-osx-mouse-trackpad-events-with-an-event-tap

**Comment by Izzatbek** [comment] 2017-02-04 09:04
Observation:
It seems that opening with `kIOHIDOptionsTypeSeizeDevice` option does return `kIOReturnSuccess`. However, the device is not being seized. I found a possible way to fix this issue by creating another device reference (and not using the devRef of the manager).
I'm not sure if this would be proper. So I will try to find another way.

**Comment by Izzatbek** [comment] 2017-02-04 15:05
It turns out we should not use manager's `IOHIDDeviceRef`. That's why there was this bug. I will commit the fix.

**Comment by Izzatbek** [comment] 2017-02-04 15:55
@casiez, I fixed the issue on the `parserImprovements` branch. Opportunistically, I fixed some potential memory leak issues. I will go ahead and merge the branch to **master**.

**Comment by Izzatbek** [comment] 2017-02-04 15:57
Closing this issue, the fix should work. However, I didn't test it with a mouse. Feel free to reopen it, if you find smth.

**Closed as completed by Izzatbek** 2017-02-04 15:57 UTC
